# general:
path: "./downloads" # folder where your songs will belong
queue: 'queue.txt' # you can use queue to download more than 1 song
verbose: true # colloquially detailed console output

# spotify:
spotify: true # enable to download spotify playlists/songs
id: "f3eff736ad844534aaf36589064ef976"
secret: "755b857a906b497e8649e9249897ea76"

# file:
format: 'mp3' # we support: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/m4v/mov
thumbnail: true # download song with thumbnail
file_name: '%(title)s' # song naming convention
quality: 128 # sound quality of the song

# network:
proxy: false # you can use your own proxies
proxies:
  - '' # here you can put your proxies

# others:
multiprocessing: true # use of multiple cpu cores
