# general:
path: "./downloads" # folder where your songs will belong
queue: 'queue.txt' # you can use queue to download more than 1 song

# spotify:
spotify: true # enable to download spotify playlists/songs
id: "fill this in"
secret: "and this"

# file:
format: 'bestaudio/best' # overall quality of the song
codec: 'mp3' # we support: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/m4v/mov
thumbnail: true # download song with thumbnail
file_name: '%(title)s' # song naming convention
bitrate: 128 # sound quality of the song

# networking:
proxy: false # you can use your own proxies
proxies:
  - '' # here you can put your proxies

# performance:
pools: true # concurrent parallel downloads (ThreadPoolExecutor)
threads: 4 # maximum amount of threads used by ThreadPoolExecutor
downloader: 'aria2c' # change this only if you know what you're doing
downloader_args: ['-x', '16', '-k', '1M'] # -x = connections, -k = chunks in MB
http_chunk_size: 1024 # fragmentation of song into chunks (Kb)
caching: true # speed up of repetitive and avoiding retries