# general:
path: "./downloads" # folder where your songs will belong
queue: 'queue.txt' # you can use queue to download more than 1 song
verbose: true # colloquially detailed console output

# spotify:
spotify: true # enable to download spotify playlists/songs
id: "insert your client id"
secret: "as well as secret"

# file:
format: 'mp3' # we support: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/m4v/mov
thumbnail: true # thumbnail of the song
file_name: '%(title)s' # the default song name
quality: 128 # sound quality of the song